export { Home as PageHome } from "./Home"
export { List as PageList } from "./List"
export { Layout as PageLayout } from "./Layout"
export { Cadastrar as PageCadastrar } from "./Cadastrar"
export { Login as PageLogin } from "./Login"